In [3]:
import numpy as np

# 차원

In [4]:
# 차원 - 미니 퀘스트
# 배열의 차원 수를 출력하는 코드
array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(array.ndim)

3


In [5]:
# 차원 - 미니 퀘스트 2번
# 1차원 배열을 2차원 배열로 변환하여 (2, 3) 형태로 출력하는 코드
array = np.array([10, 20, 30, 40, 50, 60])

new_array = array.reshape(2,3)
print(new_array)

[[10 20 30]
 [40 50 60]]


In [6]:
# 차원 - 미니 퀘스트 3번
# 1차원 배열에 새로운 차원을 추가하여 2차원 배열로 변환하고, 최종 배열의 차원 수를 출력
# newaxis 사용하여 배열의 차원을 추가하고, 새로운 차원에서의 배열 모양을 확인한 후 최종 차원 수를 출력
array = np.array([7, 14, 21])

new_vector = array[ : , np.newaxis]

print(new_vector)
print(new_vector.shape)
print(new_vector.ndim)

[[ 7]
 [14]
 [21]]
(3, 1)
2


# Shape

In [7]:
# Shape - 미니 퀘스트 1번
# 2차원 NumPy 배열의 형태(Shape)를 출력하는 코드
array = np.array([[1, 2, 3], [4, 5, 6]])

print(array.shape)

(2, 3)


In [8]:
# Shape - 미니 퀘스트 2번
# 1차원 배열을 (2, 3) 형태로 변경한 후, 새로운 배열의 형태를 출력하는 코드
array = np.array([10, 20, 30, 40, 50, 60])

array_2d = array.reshape(2, 3)
print(array_2d)


[[10 20 30]
 [40 50 60]]


In [9]:
# Shape - 미니 퀘스트 3번
# 1차원 배열의 형태를 변경하여 (3, 2, 2)형태로 조정하고, 최종 배열의 형태를 출력하는 코드
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

array_2d = array.reshape(3,2,2)
print(array_2d)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


# 데이터 타입

In [10]:
# 데이터 타입 - 미니 퀘스트 1번
# 배열의 데이터 타입을 확인하는 코드
array = np.array([10, 20, 30])

print(array.dtype)

int64


In [11]:
# 데이터 타입 - 미니 퀘스트 2번
# 정수형 배열을 부동소수점형 배열로 변환하고, 변환된 배열의 데이터 타입을 출력하는 코드
array = np.array([1, 2, 3])

print(f"변환 전 데이터 타입 : {array.dtype}")
converted_array = array.astype(np.float16)
print(f"변환 후 데이터 타입 : {converted_array.dtype}")

변환 전 데이터 타입 : int64
변환 후 데이터 타입 : float16


In [12]:
# 데이터 타입 - 미니 퀘스트 3번
# 배열을 uint8로 변환한 후, 메모리 사용량(바이트)을 출력하는 코드
array = np.array([100, 200, 300])

converted_array = array.astype(np.uint8)
print(f"각 요소가 차지하는 바이트 크기 : {converted_array.itemsize}")
print(f"배열 전체의 메모리 사용량 : {converted_array.nbytes}")

각 요소가 차지하는 바이트 크기 : 1
배열 전체의 메모리 사용량 : 3


# 인덱싱(Indexing)


In [13]:
# 인덱싱 - 미니 퀘스트 1번
# 1차원 배열에서 첫 번째 요소와 마지막 요소를 출력하는 코드
array = np.array([10, 20, 30, 40, 50])

# 팬시 인덱싱을 이용해 여러개의 특정 요소 한 번에 선택
print(array[[0, -1]])

[10 50]


In [14]:
# 인덱싱 - 미니 퀘스트 2번
# 2차원 배열에서 첫 번째 열과 두 번째 행을 출력하는 코드
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(f"첫번째 열 : {matrix[:, 0]}")
print(f"두번째 행 : {matrix[1]}")


첫번째 열 : [1 4 7]
두번째 행 : [4 5 6]


In [15]:
# 인덱싱 - 미니 퀘스트 3번
# 배열에서 10보다 큰 요소들만 선택하고, 해당 요소들의 인덱스를 출력하는 코드
array = np.array([5, 15, 8, 20, 3, 12])

indices = np.where(array > 10)[0]
print(indices)

[1 3 5]


#연산

In [16]:
# 연산 - 미니 퀘스트 1번
# NumPy 배열에서 요소별(Element-wise) 덧셈을 수행하는 코드
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)

[5 7 9]


In [17]:
# 연산 - 미니 퀘스트 2번
# NumPy 배열에서 브로드캐스팅을 활용하여 각 행에 [1, 2, 3]을 더하는 코드
matrix = np.array([[10, 20, 30], [40, 50, 60]])
vector = np.array([1, 2, 3])

print(matrix + vector)

[[11 22 33]
 [41 52 63]]


In [18]:
# 연산 - 미니 퀘스트 3번
# NumPy 배열에 대해, 축(axis)을 기준으로 최댓값을 구하고 최종 배열의 차원을 출력하는 코드
array = np.array([[3, 7, 2], [8, 4, 6]])

# axis = 0 / 즉, 세로축 기준(열)
max_axis0 = np.max(array, axis = 0)
# axis = 1 / 즉, 가로축 기준(행)
max_axis1 = np.max(array, axis = 1)

print(max_axis0)
print(max_axis1)

[8 7 6]
[7 8]


#유니버셜 함수

In [19]:
# 유니버셜 함수 - 미니 퀘스트 1번
# 배열에 대해 유니버셜 함수를 사용하여 모든 요소 제곱한 결과 출력하는 코드
array = np.array([1, 2, 3, 4])

# multiply 활용
# print(np.multiply(array,array))

print(np.square(array))

[ 1  4  9 16]


In [20]:
# 유니버셜 함수 - 미니 퀘스트 2번
# 두 배열의 요소별 합을 계산하고, 결과를 새로운 배열이 아닌 기존 배열에 저장하는 코드
array1 = np.array([10, 20, 30])
array2 = np.array([1, 2, 3])

np.add(array1, array2, out=array1)
print(array1)

[11 22 33]


In [21]:
# 유니버셜 함수 - 미니 퀘스트 3번
# 배열에 대해 NumPy 유니버설 함수를 사용하여 요소별로 자연로그(log)를 계산하고,
# 특정 조건(log 값 > 1)을 만족하는 요소만 출력하는 코드
array = np.array([1, np.e, 10, 100])

np.log(array, out=array)
array = array[array > 1]
print(array)

[2.30258509 4.60517019]
